### ISSUE TITLE
sealos can not change version 

### ISSUE THREAD

**Issue by xiao-jay** [labring/sealos-action#4]
if change version from 4.1.3 to 4.1.4,will get error 
job link: https://github.com/xiao-jay/sealos/actions/runs/4122713301/jobs/7119827481
![image](https://user-images.githubusercontent.com/87080562/217491447-d7068393-e250-4a32-be40-527bb5796492.png)

**Comment by cuisongliu** [comment]
https://github.com/marketplace/actions/auto-setup-sealos
